# Generated by Django 5.1.1 on 2024-11-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
