# Generated by Django 5.1.1 on 2024-11-08 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_ingredient_slug_phase_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcategory',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='description',
        ),
        migrations.CreateModel(
            name='PhaseFoodCategoryIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.foodcategory')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.ingredient')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.phase')),
            ],
            options={
                'unique_together': {('phase', 'food_category', 'ingredient')},
            },
        ),
    ]
